version: '3'
services:
  python-app:
      image: python:3.10
      volumes:
        - ./:/app
      working_dir: /app
      depends_on:
        - db
      command: bash -c "pip3 install -r requirements.txt;python3 ./main.py"
      
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    expose:
      - 5432
    